# Generated by Django 4.2.4 on 2023-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(default='pexels-alex-andrews-1983037', upload_to=''),
        ),
    ]
